import { Contracts } from '../../existingContracts/compound.json';

import { ChainLinkAggregators, WBTCWhale, WhaleAccount, UNIWhale } from '../../utils/constants-Additions';

export const psLoanStagesTestCases = [
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.DAI,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: Contracts.cDAI,
        liquidityCollateralTokenParam: Contracts.cWBTC2,
        chainlinkBorrowParam: ChainLinkAggregators['DAI/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.UNI,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: Contracts.cUNI,
        liquidityCollateralTokenParam: Contracts.cWBTC2,
        chainlinkBorrowParam: ChainLinkAggregators['UNI/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDC,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: Contracts.cUSDC,
        liquidityCollateralTokenParam: Contracts.cWBTC2,
        chainlinkBorrowParam: ChainLinkAggregators['USDC/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 1,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDT,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: Contracts.cUSDT,
        liquidityCollateralTokenParam: Contracts.cWBTC2,
        chainlinkBorrowParam: ChainLinkAggregators['USDT/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 10,
        Whale1: WBTCWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.Comp,
        CollateralTokenParam: Contracts.WBTC,
        liquidityBorrowTokenParam: Contracts.cComp,
        liquidityCollateralTokenParam: Contracts.cWBTC2,
        chainlinkBorrowParam: ChainLinkAggregators['COMP/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['BTC/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDC,
        CollateralTokenParam: Contracts.UNI,
        liquidityBorrowTokenParam: Contracts.cUSDC,
        liquidityCollateralTokenParam: Contracts.cUNI,
        chainlinkBorrowParam: ChainLinkAggregators['USDC/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['UNI/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDT,
        CollateralTokenParam: Contracts.UNI,
        liquidityBorrowTokenParam: Contracts.cUSDT,
        liquidityCollateralTokenParam: Contracts.cUNI,
        chainlinkBorrowParam: ChainLinkAggregators['USDT/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['UNI/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.DAI,
        CollateralTokenParam: Contracts.UNI,
        liquidityBorrowTokenParam: Contracts.cDAI,
        liquidityCollateralTokenParam: Contracts.cUNI,
        chainlinkBorrowParam: ChainLinkAggregators['DAI/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['UNI/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.DAI,
        CollateralTokenParam: Contracts.Comp,
        liquidityBorrowTokenParam: Contracts.cDAI,
        liquidityCollateralTokenParam: Contracts.cComp,
        chainlinkBorrowParam: ChainLinkAggregators['DAI/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['COMP/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDC,
        CollateralTokenParam: Contracts.Comp,
        liquidityBorrowTokenParam: Contracts.cUSDC,
        liquidityCollateralTokenParam: Contracts.cComp,
        chainlinkBorrowParam: ChainLinkAggregators['USDC/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['COMP/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.USDT,
        CollateralTokenParam: Contracts.Comp,
        liquidityBorrowTokenParam: Contracts.cUSDT,
        liquidityCollateralTokenParam: Contracts.cComp,
        chainlinkBorrowParam: ChainLinkAggregators['USDT/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['COMP/USD'],
    },
    {
        Amount: 100,
        Whale1: UNIWhale,
        Whale2: WhaleAccount,
        BorrowTokenParam: Contracts.UNI,
        CollateralTokenParam: Contracts.Comp,
        liquidityBorrowTokenParam: Contracts.cUNI,
        liquidityCollateralTokenParam: Contracts.cComp,
        chainlinkBorrowParam: ChainLinkAggregators['UNI/USD'],
        chainlinkCollateralParam: ChainLinkAggregators['COMP/USD'],
    },
    // investigate why the below thing is failing
    // {
    //     Amount: 1,
    //     Whale1: '0xE93381fB4c4F14bDa253907b18faD305D799241a', //houbi 10
    //     Whale2: '0xE93381fB4c4F14bDa253907b18faD305D799241a', // houbi 10
    //     BorrowTokenParam: '0x6b3595068778dd592e39a122f4f5a5cf09c90fe2', // sushi
    //     CollateralTokenParam: '0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e', //yfi
    //     liquidityBorrowTokenParam: '0x4b0181102a0112a2ef11abee5563bb4a3176c9d7', //csushi
    //     liquidityCollateralTokenParam: '0x80a2ae356fc9ef4305676f7a3e2ed04e12c33946', //cyfi
    //     chainlinkBorrowParam: '0xCc70F09A6CC17553b2E31954cD36E4A2d89501f7',
    //     chainlinkCollateralParam: '0xA027702dbb89fbd58938e4324ac03B58d812b0E1',
    // },
];
